### ISSUE TITLE
UTF-8 Chars and OKHttp 2.6

### ISSUE THREAD

**Issue by NLLAPPS** [dropbox/dropbox-sdk-java-v2#2]
As pper https://github.com/square/okhttp/issues/2016 OKHtttp is more restrict with HTTP headers and all non ASCII file names causes crash on beta 3 when used with OKHttp 2.6.
Everything is OK with 2.4

In did try to use URLEncoder ( http://developer.android.com/reference/java/net/URLEncoder.html ) before upload, but this caused file name to be double encoded

**Comment by NLLAPPS** [comment]
Here is a sample stack trace

STACK_TRACE=java.lang.IllegalArgumentException: Unexpected char 0x410 at 10 in header value: {"path":"/риценко.mp4","mode":{".tag":"overwrite"},"autorename":false,"mute":false}
at com.squareup.okhttp.Headers$Builder.checkNameAndValue(SourceFile:295)
at com.squareup.okhttp.Headers$Builder.add(SourceFile:245)
at com.squareup.okhttp.Request$Builder.addHeader(SourceFile:194)
at com.dropbox.core.http.OkHttpRequestor.toOkHttpHeaders(SourceFile:91)
at com.dropbox.core.http.OkHttpRequestor.startUpload(SourceFile:84)
at com.dropbox.core.http.OkHttpRequestor.startPost(SourceFile:69)
at com.dropbox.core.http.OkHttpRequestor.startPost(SourceFile:30)
at com.dropbox.core.v2.DbxRawClientV2.uploadStyle(SourceFile:169)
at com.dropbox.core.v2.DbxFiles.upload(SourceFile:8176)
at com.dropbox.core.v2.DbxFiles.access$5900(SourceFile:25)
at com.dropbox.core.v2.DbxFiles$UploadBuilder.start(SourceFile:8224)
at com.dropbox.core.v2.DbxFiles$UploadBuilder.start(SourceFile:8190)
at com.dropbox.core.v2.DbxUploadStyleBuilder.run(SourceFile:29)
at dhy.a(SourceFile:56)
at dhb.a(SourceFile:123)
at com.nll.cloud.DroboxV2IntentService.a(SourceFile:43)
at dfv.a(SourceFile:97)
at dfv.onHandleIntent(SourceFile:58)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by cakoose** [comment]
We just switched to using ASCII-only in beta-4, so hopefully that works for you.  (When I switched to ASCII-only I didn't think anyone would be immediately affected since the previous code worked for me, but I never tested OkHttp :-)

BTW, this repo is deprecated.  You should use "dropbox-sdk-java" repo instead.
